# -*- coding: utf-8 -*-
"""sea_level_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13iEcAED5VQmFNvb9DIR6B5D0QBa6W2Ny
"""

import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import linregress
import numpy as np


def draw_plot():
    # Import data
    df = pd.read_csv("epa-sea-level.csv")

    # Create scatter plot
    fig, ax = plt.subplots(figsize=(10, 6))
    ax.scatter(df["Year"], df["CSIRO Adjusted Sea Level"])

    # First line of best fit (all data)
    result = linregress(df["Year"], df["CSIRO Adjusted Sea Level"])

    years = np.arange(df["Year"].min(), 2051)

    ax.plot(
        years,
        result.slope * years + result.intercept,
        color="red",
    )

    # Second line of best fit (from year 2000 onward)
    recent = df[df["Year"] >= 2000]

    result_recent = linregress(
        recent["Year"],
        recent["CSIRO Adjusted Sea Level"],
    )

    years_recent = np.arange(2000, 2051)

    ax.plot(
        years_recent,
        result_recent.slope * years_recent + result_recent.intercept,
        color="green",
    )

    # Labels and title
    ax.set_xlabel("Year")
    ax.set_ylabel("Sea Level (inches)")
    ax.set_title("Rise in Sea Level")

    # Save and return
    fig.savefig("sea_level_plot.png")
    return fig